### ISSUE TITLE
Ankety zobrazuji pouze jednoho hlasujiciho

### ISSUE THREAD

**Issue by Martian-0007** [TheXer/Jachym#29]
**Popiš bug co nejjasněji!**
Kdyz hlasuje vice lidi v ankete, je videt pouze ten posledni kdo hlasoval pro danou moznost

**Jak jsi reprodukoval bug? Jde to reprodukovat?**
S Elfem jsme vytvorili anketu a hlasovali

**Očekávané chování**
Zobrazi vsechny kdo hlasovaly pro danou moznost

**Nějaké další informace, co bychom měli vědět?**
Test probehl v Discord serveru

**Comment by TheXer** [comment]
**Reprodukce bugu je následovná:** 

1. Vytvořit anketu s pomocí /anketa
2. Hlasovat na jedno tlačítko - ideálně dva lidi naráz
3. Embed nestíhá zpracovávat requesty, tak zobrazí jen posledního hlasujícího bez dalších lidí 
4. Ostatní tlačítka fungují při hlasování, hlas se zobrazí, ale nelze odhlasovat zpět, hlas tam zůstane

Při vytvoření nových anket poté fungují hlasy, ale nejde odhlasovat. 

**Možný problém:** 
Databáze nyní zpracovává requesty po jednom, tzn. někdo bude hlasovat, jeho hlas se přidá do db, druhý začne hlasovat, jeho hlas se také přidá do db, ale pokud dva lidi naráz spamují hlasy, tak databáze nestíhá přidávat a vyndávat hlasy, což vyústí v jeho korupci dat. 

**Možné řešení problému**
Jednou z možností je vytvořit Queue třídu, která by do fronty přidávala hlasy (případně její odhlasování) a databáze jej zpracovávala svým tempem. Další z možností je `asyncio.create_task()`, podívat se na to do dokumentace.

**Comment by TheXer** [comment]
Closed
